application: nvirdy-studious
version: 1
runtime: php
api_version: 1

handlers:
- url: /
  script: index.php

- url: /index\.php
  script: index.php

- url: /search\.php
  script: search.php

- url: /about\.html
  script: about.html

- url: /contact\.html
  script: contact.html

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: not_found.php